-- Strengthen assessment differentiation by adding direct role signals to
-- scale and adaptive stage options without changing endpoint contracts.

UPDATE assessment_options SET weight_json='{"LOGICAL":1,"ANALYTICAL":1,"DATA_ANALYST":1}' WHERE id=2025;
UPDATE assessment_options SET weight_json='{"LOGICAL":2,"ANALYTICAL":2,"DATA_ANALYST":1,"BUSINESS_ANALYST":1}' WHERE id=2026;
UPDATE assessment_options SET weight_json='{"LOGICAL":3,"ANALYTICAL":3,"DATA_ANALYST":2,"DATA_SCIENCE":1,"BUSINESS_ANALYST":1}' WHERE id=2027;
UPDATE assessment_options SET weight_json='{"LOGICAL":4,"ANALYTICAL":4,"DATA_SCIENCE":2,"DATA_SCIENTIST":2,"AI_ML_ENGINEER":2}' WHERE id=2028;
UPDATE assessment_options SET weight_json='{"LOGICAL":5,"ANALYTICAL":5,"DATA_SCIENCE":3,"DATA_SCIENTIST":3,"AI_ML_ENGINEER":3}' WHERE id=2029;

UPDATE assessment_options SET weight_json='{"LOGICAL":1,"DETAIL_ORIENTED":1,"OPERATIONS_ORIENTED":1,"FRONTEND_DEVELOPER":1}' WHERE id=2030;
UPDATE assessment_options SET weight_json='{"LOGICAL":2,"DETAIL_ORIENTED":1,"OPERATIONS_ORIENTED":1,"SOFTWARE_ENGINEERING":1,"FRONTEND_DEVELOPER":1}' WHERE id=2031;
UPDATE assessment_options SET weight_json='{"LOGICAL":3,"DETAIL_ORIENTED":2,"OPERATIONS_ORIENTED":2,"SOFTWARE_ENGINEERING":1,"JAVA_BACKEND_DEVELOPER":1,"FULL_STACK_DEVELOPER":1}' WHERE id=2032;
UPDATE assessment_options SET weight_json='{"LOGICAL":4,"DETAIL_ORIENTED":3,"OPERATIONS_ORIENTED":3,"SOFTWARE_ENGINEERING":2,"JAVA_BACKEND_DEVELOPER":2,"FULL_STACK_DEVELOPER":2,"DEVOPS_ENGINEER":1}' WHERE id=2033;
UPDATE assessment_options SET weight_json='{"LOGICAL":5,"DETAIL_ORIENTED":4,"OPERATIONS_ORIENTED":4,"SOFTWARE_ENGINEERING":3,"JAVA_BACKEND_DEVELOPER":3,"FULL_STACK_DEVELOPER":3,"DEVOPS_ENGINEER":2}' WHERE id=2034;

UPDATE assessment_options SET weight_json='{"COMMUNICATION":1,"STRATEGIC":1,"DATA_ANALYST":1}' WHERE id=2040;
UPDATE assessment_options SET weight_json='{"COMMUNICATION":2,"STRATEGIC":1,"PRODUCT_MANAGER":1,"BUSINESS_ANALYST":1}' WHERE id=2041;
UPDATE assessment_options SET weight_json='{"COMMUNICATION":3,"STRATEGIC":2,"PRODUCT_MANAGER":2,"PRODUCT_MANAGEMENT":2,"BUSINESS_ANALYST":2}' WHERE id=2042;
UPDATE assessment_options SET weight_json='{"COMMUNICATION":4,"STRATEGIC":3,"PRODUCT_MANAGER":3,"PRODUCT_MANAGEMENT":3,"MARKETING":2,"BUSINESS_ANALYST":2}' WHERE id=2043;
UPDATE assessment_options SET weight_json='{"COMMUNICATION":5,"STRATEGIC":4,"PRODUCT_MANAGER":4,"PRODUCT_MANAGEMENT":4,"MARKETING":3,"BUSINESS_ANALYST":3}' WHERE id=2044;

UPDATE assessment_options SET weight_json='{"SECURITY_ORIENTED":1,"OPERATIONS_ORIENTED":1,"DETAIL_ORIENTED":1,"QA_ENGINEER":1}' WHERE id=2050;
UPDATE assessment_options SET weight_json='{"SECURITY_ORIENTED":2,"OPERATIONS_ORIENTED":1,"DETAIL_ORIENTED":1,"QA_ENGINEER":1,"CYBERSECURITY_ANALYST":1}' WHERE id=2051;
UPDATE assessment_options SET weight_json='{"SECURITY_ORIENTED":3,"OPERATIONS_ORIENTED":2,"DETAIL_ORIENTED":2,"QA_ENGINEER":2,"CYBERSECURITY_ANALYST":2,"DEVOPS_ENGINEER":1}' WHERE id=2052;
UPDATE assessment_options SET weight_json='{"SECURITY_ORIENTED":4,"OPERATIONS_ORIENTED":3,"DETAIL_ORIENTED":3,"CYBERSECURITY_ANALYST":3,"DEVOPS_ENGINEER":2,"QA_ENGINEER":2}' WHERE id=2053;
UPDATE assessment_options SET weight_json='{"SECURITY_ORIENTED":5,"OPERATIONS_ORIENTED":4,"DETAIL_ORIENTED":4,"CYBERSECURITY_ANALYST":4,"DEVOPS_ENGINEER":3,"QA_ENGINEER":3}' WHERE id=2054;

UPDATE assessment_options SET weight_json='{"LOGICAL":4,"DETAIL_ORIENTED":3,"OPERATIONS_ORIENTED":2,"SOFTWARE_ENGINEERING":2,"JAVA_BACKEND_DEVELOPER":2,"FULL_STACK_DEVELOPER":1}' WHERE id=2055;
UPDATE assessment_options SET weight_json='{"LOGICAL":4,"OPERATIONS_ORIENTED":3,"DETAIL_ORIENTED":2,"JAVA_BACKEND_DEVELOPER":2,"DEVOPS_ENGINEER":2,"SOFTWARE_ENGINEERING":1}' WHERE id=2056;
UPDATE assessment_options SET weight_json='{"CREATIVE":3,"COMMUNICATION":2,"LOGICAL":2,"FRONTEND_DEVELOPER":2,"FULL_STACK_DEVELOPER":1,"UI_UX_DESIGNER":1}' WHERE id=2057;
UPDATE assessment_options SET weight_json='{"DETAIL_ORIENTED":3,"OPERATIONS_ORIENTED":3,"COMMUNICATION":2,"QA_ENGINEER":3,"DEVOPS_ENGINEER":2,"SOFTWARE_ENGINEERING":1}' WHERE id=2058;

UPDATE assessment_options SET weight_json='{"ANALYTICAL":5,"LOGICAL":3,"DETAIL_ORIENTED":2,"DATA_SCIENCE":3,"DATA_SCIENTIST":3,"AI_ML_ENGINEER":2}' WHERE id=2059;
UPDATE assessment_options SET weight_json='{"ANALYTICAL":4,"COMMUNICATION":3,"STRATEGIC":2,"DATA_ANALYST":3,"BUSINESS_ANALYST":2,"PRODUCT_MANAGER":1}' WHERE id=2060;
UPDATE assessment_options SET weight_json='{"ANALYTICAL":4,"STRATEGIC":3,"COMMUNICATION":3,"BUSINESS_ANALYST":3,"PRODUCT_MANAGER":2,"PRODUCT_MANAGEMENT":2}' WHERE id=2061;
UPDATE assessment_options SET weight_json='{"ANALYTICAL":4,"OPERATIONS_ORIENTED":3,"DETAIL_ORIENTED":2,"DEVOPS_ENGINEER":1,"AI_ML_ENGINEER":2,"DATA_SCIENCE":1}' WHERE id=2062;

UPDATE assessment_options SET weight_json='{"STRATEGIC":5,"COMMUNICATION":4,"ANALYTICAL":2,"PRODUCT_MANAGER":4,"PRODUCT_MANAGEMENT":4}' WHERE id=2063;
UPDATE assessment_options SET weight_json='{"COMMUNICATION":4,"STRATEGIC":3,"CREATIVE":2,"MARKETING":4,"PRODUCT_MANAGER":2}' WHERE id=2064;
UPDATE assessment_options SET weight_json='{"ANALYTICAL":4,"COMMUNICATION":3,"DETAIL_ORIENTED":2,"BUSINESS_ANALYST":4,"DATA_ANALYST":2}' WHERE id=2065;
UPDATE assessment_options SET weight_json='{"STRATEGIC":4,"COMMUNICATION":4,"DETAIL_ORIENTED":2,"PRODUCT_MANAGER":3,"PRODUCT_MANAGEMENT":3,"BUSINESS_ANALYST":1}' WHERE id=2066;

UPDATE assessment_options SET weight_json='{"CREATIVE":5,"COMMUNICATION":3,"DETAIL_ORIENTED":2,"UI_UX_DESIGNER":4,"DESIGN":4}' WHERE id=2067;
UPDATE assessment_options SET weight_json='{"CREATIVE":5,"DETAIL_ORIENTED":3,"ANALYTICAL":2,"UI_UX_DESIGNER":3,"DESIGN":3,"FRONTEND_DEVELOPER":1}' WHERE id=2068;
UPDATE assessment_options SET weight_json='{"CREATIVE":3,"LOGICAL":3,"DETAIL_ORIENTED":2,"FRONTEND_DEVELOPER":3,"FULL_STACK_DEVELOPER":1}' WHERE id=2069;
UPDATE assessment_options SET weight_json='{"CREATIVE":4,"STRATEGIC":3,"COMMUNICATION":2,"UI_UX_DESIGNER":2,"DESIGN":2,"PRODUCT_MANAGER":1}' WHERE id=2070;

UPDATE assessment_options SET weight_json='{"SECURITY_ORIENTED":5,"OPERATIONS_ORIENTED":3,"DETAIL_ORIENTED":2,"CYBERSECURITY_ANALYST":4,"DEVOPS_ENGINEER":2}' WHERE id=2071;
UPDATE assessment_options SET weight_json='{"OPERATIONS_ORIENTED":4,"SECURITY_ORIENTED":4,"LOGICAL":2,"DEVOPS_ENGINEER":4,"CYBERSECURITY_ANALYST":2}' WHERE id=2072;
UPDATE assessment_options SET weight_json='{"DETAIL_ORIENTED":4,"OPERATIONS_ORIENTED":3,"SECURITY_ORIENTED":2,"QA_ENGINEER":4,"DEVOPS_ENGINEER":1}' WHERE id=2073;
UPDATE assessment_options SET weight_json='{"SECURITY_ORIENTED":4,"STRATEGIC":2,"DETAIL_ORIENTED":3,"CYBERSECURITY_ANALYST":3,"BUSINESS_ANALYST":1,"QA_ENGINEER":1}' WHERE id=2074;
