CREATE TABLE IF NOT EXISTS technical_assessment_questions (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    career_track VARCHAR(100) NOT NULL,
    skill_area VARCHAR(160) NOT NULL,
    difficulty VARCHAR(30) NOT NULL,
    question_text VARCHAR(2000) NOT NULL,
    explanation VARCHAR(2000) NULL,
    display_order INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_technical_assessment_question_track_order UNIQUE (career_track, display_order)
);

CREATE TABLE IF NOT EXISTS technical_assessment_options (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    question_id BIGINT NOT NULL,
    option_text VARCHAR(1000) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    sort_order INT NOT NULL,
    CONSTRAINT fk_technical_assessment_option_question
        FOREIGN KEY (question_id) REFERENCES technical_assessment_questions(id)
        ON DELETE CASCADE,
    CONSTRAINT uk_technical_assessment_option_question_sort UNIQUE (question_id, sort_order)
);

CREATE INDEX idx_technical_assessment_question_track_active
    ON technical_assessment_questions(career_track, active, display_order);

INSERT INTO technical_assessment_questions (id, career_track, skill_area, difficulty, question_text, explanation, display_order, active) VALUES
(1001, 'JAVA_BACKEND_DEVELOPER', 'API Design', 'FOUNDATION', 'A POST /orders endpoint successfully creates a new order. Which response contract is most correct?', NULL, 1, TRUE),
(1002, 'JAVA_BACKEND_DEVELOPER', 'Spring Architecture', 'FOUNDATION', 'You publish a domain event only if the surrounding transaction commits. Which Spring mechanism is designed for that?', NULL, 2, TRUE),
(1003, 'JAVA_BACKEND_DEVELOPER', 'Persistence', 'APPLIED', 'A JPA service loads 50 orders, then triggers one extra SQL query per order to read line items. What issue are you seeing?', NULL, 3, TRUE),
(1004, 'JAVA_BACKEND_DEVELOPER', 'Security', 'APPLIED', 'Which approach is correct for storing user passwords in a backend system?', NULL, 4, TRUE),
(1005, 'JAVA_BACKEND_DEVELOPER', 'API Design', 'APPLIED', 'A client may retry a payment request because of a timeout. What backend pattern best prevents duplicate charges?', NULL, 5, TRUE),
(1006, 'JAVA_BACKEND_DEVELOPER', 'Persistence', 'APPLIED', 'Two users update the same entity concurrently and the second update should fail if the row changed after it was read. What is the standard JPA solution?', NULL, 6, TRUE),
(1007, 'JAVA_BACKEND_DEVELOPER', 'Spring Architecture', 'ARCHITECTURE', 'Generating a large PDF report takes 90 seconds and currently runs inside the request thread. What architecture is more appropriate?', NULL, 7, TRUE),
(1008, 'JAVA_BACKEND_DEVELOPER', 'Security', 'ARCHITECTURE', 'A frontend hides admin buttons, but the backend also has admin endpoints. What must the backend still do on every protected request?', NULL, 8, TRUE),

(2001, 'FRONTEND_DEVELOPER', 'Performance', 'FOUNDATION', 'The largest contentful paint on your landing page is a hero image. Which change usually helps first?', NULL, 1, TRUE),
(2002, 'FRONTEND_DEVELOPER', 'Accessibility', 'FOUNDATION', 'A form field only uses placeholder text and has no visible label. What is the main problem?', NULL, 2, TRUE),
(2003, 'FRONTEND_DEVELOPER', 'State Management', 'APPLIED', 'A user types quickly and triggers overlapping search requests. What prevents stale responses from replacing newer results?', NULL, 3, TRUE),
(2004, 'FRONTEND_DEVELOPER', 'Security', 'APPLIED', 'What is the main security risk of placing untrusted HTML directly into innerHTML?', NULL, 4, TRUE),
(2005, 'FRONTEND_DEVELOPER', 'Performance', 'APPLIED', 'A heavy charting library is only needed on one route. What loading strategy is best?', NULL, 5, TRUE),
(2006, 'FRONTEND_DEVELOPER', 'Accessibility', 'APPLIED', 'After async form submission, what helps screen-reader users notice a success or failure message immediately?', NULL, 6, TRUE),
(2007, 'FRONTEND_DEVELOPER', 'State Management', 'ARCHITECTURE', 'A dashboard rerenders expensively because derived data is recalculated on every keystroke. What is the strongest fix?', NULL, 7, TRUE),
(2008, 'FRONTEND_DEVELOPER', 'Security', 'ARCHITECTURE', 'Where is the safest place to enforce authorization for protected business actions?', NULL, 8, TRUE),

(3001, 'FULL_STACK_DEVELOPER', 'Authentication', 'FOUNDATION', 'Where should production database credentials live?', NULL, 1, TRUE),
(3002, 'FULL_STACK_DEVELOPER', 'System Design', 'FOUNDATION', 'Why should inputs be validated on both client and server?', NULL, 2, TRUE),
(3003, 'FULL_STACK_DEVELOPER', 'System Design', 'APPLIED', 'A list page becomes slow because the API returns 20,000 records at once. What is the best first fix?', NULL, 3, TRUE),
(3004, 'FULL_STACK_DEVELOPER', 'Authentication', 'APPLIED', 'A payment provider may resend the same webhook event several times. What backend design protects against duplicate processing?', NULL, 4, TRUE),
(3005, 'FULL_STACK_DEVELOPER', 'Operations', 'APPLIED', 'Users report that a save action feels slow. What investigation path is most complete?', NULL, 5, TRUE),
(3006, 'FULL_STACK_DEVELOPER', 'Delivery', 'APPLIED', 'A feature changes the UI, API contract, and database schema. What gives the strongest protection during deployment?', NULL, 6, TRUE),
(3007, 'FULL_STACK_DEVELOPER', 'System Design', 'ARCHITECTURE', 'A request triggers image processing and email sending and keeps timing out. What is the better architecture?', NULL, 7, TRUE),
(3008, 'FULL_STACK_DEVELOPER', 'Operations', 'ARCHITECTURE', 'What makes tracing a single user action across browser, API, and worker systems much easier?', NULL, 8, TRUE),

(4001, 'DATA_SCIENTIST', 'Experiment Design', 'FOUNDATION', 'Why do we keep a test set separate from training and validation data?', NULL, 1, TRUE),
(4002, 'DATA_SCIENTIST', 'Modeling', 'FOUNDATION', 'What is overfitting?', NULL, 2, TRUE),
(4003, 'DATA_SCIENTIST', 'Experiment Design', 'APPLIED', 'For a time-series forecasting problem, what is the most appropriate split strategy?', NULL, 3, TRUE),
(4004, 'DATA_SCIENTIST', 'Data Quality', 'APPLIED', 'Which scenario is a classic example of target leakage?', NULL, 4, TRUE),
(4005, 'DATA_SCIENTIST', 'Modeling', 'APPLIED', 'For a highly imbalanced fraud dataset, which metric is usually more informative than plain accuracy?', NULL, 5, TRUE),
(4006, 'DATA_SCIENTIST', 'Data Quality', 'APPLIED', 'When should feature scaling be treated as part of a training pipeline rather than done once on the full dataset?', NULL, 6, TRUE),
(4007, 'DATA_SCIENTIST', 'Monitoring', 'ARCHITECTURE', 'Your model quality drops months after deployment because live user behavior changed. What is this called?', NULL, 7, TRUE),
(4008, 'DATA_SCIENTIST', 'Monitoring', 'ARCHITECTURE', 'What is the strongest production practice for detecting silent model degradation?', NULL, 8, TRUE),

(5001, 'DEVOPS_ENGINEER', 'CI/CD', 'FOUNDATION', 'What is infrastructure as code?', NULL, 1, TRUE),
(5002, 'DEVOPS_ENGINEER', 'Security', 'FOUNDATION', 'What does least privilege mean in cloud IAM?', NULL, 2, TRUE),
(5003, 'DEVOPS_ENGINEER', 'CI/CD', 'APPLIED', 'What should a CI pipeline do before allowing deployment to continue?', NULL, 3, TRUE),
(5004, 'DEVOPS_ENGINEER', 'Kubernetes', 'APPLIED', 'Why are readiness probes important in Kubernetes?', NULL, 4, TRUE),
(5005, 'DEVOPS_ENGINEER', 'Security', 'APPLIED', 'Where should application secrets normally be stored?', NULL, 5, TRUE),
(5006, 'DEVOPS_ENGINEER', 'Observability', 'APPLIED', 'For containerized services, where should application logs go by default?', NULL, 6, TRUE),
(5007, 'DEVOPS_ENGINEER', 'Kubernetes', 'ARCHITECTURE', 'What is a key advantage of blue-green deployment?', NULL, 7, TRUE),
(5008, 'DEVOPS_ENGINEER', 'Observability', 'ARCHITECTURE', 'What is the best definition of an SLO?', NULL, 8, TRUE);

INSERT INTO technical_assessment_options (id, question_id, option_text, is_correct, sort_order) VALUES
(10011, 1001, '200 OK with no metadata because the body is enough', FALSE, 1),
(10012, 1001, '201 Created with the new resource location and representation', TRUE, 2),
(10013, 1001, '301 Moved Permanently to the collection endpoint', FALSE, 3),
(10014, 1001, '500 Internal Server Error because a database write occurred', FALSE, 4),
(10021, 1002, 'ApplicationReadyEvent', FALSE, 1),
(10022, 1002, '@TransactionalEventListener with AFTER_COMMIT phase', TRUE, 2),
(10023, 1002, '@PostConstruct on the service bean', FALSE, 3),
(10024, 1002, 'A servlet filter that wraps the controller', FALSE, 4),
(10031, 1003, 'Deadlock caused by optimistic locking', FALSE, 1),
(10032, 1003, 'Broken JSON serialization only', FALSE, 2),
(10033, 1003, 'The N+1 query problem caused by repeated lazy loads', TRUE, 3),
(10034, 1003, 'A circular dependency between repositories', FALSE, 4),
(10041, 1004, 'Encrypt passwords with AES and decrypt during login', FALSE, 1),
(10042, 1004, 'Store passwords as plain text in a private table', FALSE, 2),
(10043, 1004, 'Store a strong one-way hash such as bcrypt or Argon2', TRUE, 3),
(10044, 1004, 'Base64-encode the password before saving it', FALSE, 4),
(10051, 1005, 'Trust the client to never retry the request', FALSE, 1),
(10052, 1005, 'Accept an idempotency key and reject duplicate payment intents', TRUE, 2),
(10053, 1005, 'Disable database constraints for the payment table', FALSE, 3),
(10054, 1005, 'Return 200 OK before any validation happens', FALSE, 4),
(10061, 1006, 'Add @Version and use optimistic locking', TRUE, 1),
(10062, 1006, 'Use String instead of Long as the primary key', FALSE, 2),
(10063, 1006, 'Load entities without transactions', FALSE, 3),
(10064, 1006, 'Serialize writes through the frontend only', FALSE, 4),
(10071, 1007, 'Increase the HTTP timeout to 120 seconds and keep the same design', FALSE, 1),
(10072, 1007, 'Run PDF generation as a background job and return a job reference', TRUE, 2),
(10073, 1007, 'Put the PDF bytes into the JWT token', FALSE, 3),
(10074, 1007, 'Move the whole task to the browser to avoid server load', FALSE, 4),
(10081, 1008, 'Trust that the UI already hid the admin buttons', FALSE, 1),
(10082, 1008, 'Only validate admin access in a nightly batch job', FALSE, 2),
(10083, 1008, 'Enforce authorization server-side for every protected request', TRUE, 3),
(10084, 1008, 'Allow the request but hide sensitive fields in the response', FALSE, 4),

(20011, 2001, 'Preload and properly size the hero image while serving an optimized format', TRUE, 1),
(20012, 2001, 'Move all CSS into inline styles regardless of size', FALSE, 2),
(20013, 2001, 'Add more third-party scripts before the image loads', FALSE, 3),
(20014, 2001, 'Render the image only after a user clicks the page', FALSE, 4),
(20021, 2002, 'Placeholders are fine because assistive tech reads them as labels forever', FALSE, 1),
(20022, 2002, 'The field has weaker accessibility because placeholder text is not a reliable label', TRUE, 2),
(20023, 2002, 'The field will automatically become required', FALSE, 3),
(20024, 2002, 'Only color contrast is affected', FALSE, 4),
(20031, 2003, 'Ignore ordering and always render the last response that arrives', FALSE, 1),
(20032, 2003, 'Abort or invalidate older requests before applying their results', TRUE, 2),
(20033, 2003, 'Use localStorage for all network responses', FALSE, 3),
(20034, 2003, 'Disable debouncing forever', FALSE, 4),
(20041, 2004, 'Cross-site scripting because attacker-controlled scripts can run', TRUE, 1),
(20042, 2004, 'Only slower repaint performance', FALSE, 2),
(20043, 2004, 'Automatic layout thrashing', FALSE, 3),
(20044, 2004, 'A database deadlock', FALSE, 4),
(20051, 2005, 'Bundle it into the main chunk so every user downloads it up front', FALSE, 1),
(20052, 2005, 'Load it lazily through route-level code splitting or dynamic import', TRUE, 2),
(20053, 2005, 'Inline the library source directly in HTML', FALSE, 3),
(20054, 2005, 'Ship the library in a cookie to reduce JS requests', FALSE, 4),
(20061, 2006, 'Use an aria-live region for status updates', TRUE, 1),
(20062, 2006, 'Flash the screen background color very quickly', FALSE, 2),
(20063, 2006, 'Only show the message as an icon', FALSE, 3),
(20064, 2006, 'Hide the message until the next page reload', FALSE, 4),
(20071, 2007, 'Memoize expensive derived computations and reduce unnecessary rerenders', TRUE, 1),
(20072, 2007, 'Rebuild the entire DOM tree on every keypress', FALSE, 2),
(20073, 2007, 'Move all state into global variables without ownership rules', FALSE, 3),
(20074, 2007, 'Avoid profiling because it is only for backend work', FALSE, 4),
(20081, 2008, 'Inside the client only because users never inspect network calls', FALSE, 1),
(20082, 2008, 'On the server for every protected action, regardless of what the UI shows', TRUE, 2),
(20083, 2008, 'Inside CSS classes tied to hidden buttons', FALSE, 3),
(20084, 2008, 'Only in analytics events after the request succeeds', FALSE, 4),

(30011, 3001, 'In environment variables or a managed secret store', TRUE, 1),
(30012, 3001, 'Hard-coded into frontend JavaScript for easier access', FALSE, 2),
(30013, 3001, 'Committed directly to the repository because the repo is private', FALSE, 3),
(30014, 3001, 'Embedded in each SQL query string', FALSE, 4),
(30021, 3002, 'Client validation improves UX while server validation protects business rules', TRUE, 1),
(30022, 3002, 'It is not necessary to validate on the server if the client uses TypeScript', FALSE, 2),
(30023, 3002, 'Validation is only useful for forms, not APIs', FALSE, 3),
(30024, 3002, 'Server validation mainly improves CSS rendering speed', FALSE, 4),
(30031, 3003, 'Add pagination, filtering, and sensible defaults', TRUE, 1),
(30032, 3003, 'Return even more records to reduce client requests', FALSE, 2),
(30033, 3003, 'Disable authentication to save CPU time', FALSE, 3),
(30034, 3003, 'Convert the payload to plain text only', FALSE, 4),
(30041, 3004, 'Track provider event IDs and ignore already-processed events', TRUE, 1),
(30042, 3004, 'Trust that the provider never retries', FALSE, 2),
(30043, 3004, 'Delete the event record after each request before committing', FALSE, 3),
(30044, 3004, 'Process webhook events only in the browser', FALSE, 4),
(30051, 3005, 'Inspect browser timings, API latency, and database performance together', TRUE, 1),
(30052, 3005, 'Change only the button color and retest', FALSE, 2),
(30053, 3005, 'Assume the problem is always on the user device', FALSE, 3),
(30054, 3005, 'Delete all logs to speed up the server', FALSE, 4),
(30061, 3006, 'Run automated tests and controlled schema migrations in CI before release', TRUE, 1),
(30062, 3006, 'Deploy straight from a developer laptop without checks', FALSE, 2),
(30063, 3006, 'Skip database migrations and patch rows manually in production', FALSE, 3),
(30064, 3006, 'Only test the frontend because the API is unchanged in spirit', FALSE, 4),
(30071, 3007, 'Use asynchronous jobs or events for long-running post-processing work', TRUE, 1),
(30072, 3007, 'Keep everything inside the synchronous request until it finishes', FALSE, 2),
(30073, 3007, 'Store binary images in browser localStorage before the API responds', FALSE, 3),
(30074, 3007, 'Move the database writes into the CDN edge cache', FALSE, 4),
(30081, 3008, 'Correlation IDs propagated across services and logs', TRUE, 1),
(30082, 3008, 'Renaming variables in the frontend only', FALSE, 2),
(30083, 3008, 'Disabling tracing headers to reduce all observability data', FALSE, 3),
(30084, 3008, 'Serving the same static response for every request', FALSE, 4),

(40011, 4001, 'To estimate final generalization on unseen data', TRUE, 1),
(40012, 4001, 'To memorize labels one last time before deployment', FALSE, 2),
(40013, 4001, 'To replace validation entirely', FALSE, 3),
(40014, 4001, 'To improve notebook rendering speed', FALSE, 4),
(40021, 4002, 'The model fits training patterns so tightly that it performs poorly on new data', TRUE, 1),
(40022, 4002, 'The model has too few rows to train at all', FALSE, 2),
(40023, 4002, 'The model only works for regression', FALSE, 3),
(40024, 4002, 'The model stores data in parquet format', FALSE, 4),
(40031, 4003, 'Randomly shuffle all rows and split by percentage', FALSE, 1),
(40032, 4003, 'Train on earlier periods and validate on later periods', TRUE, 2),
(40033, 4003, 'Use the test set for hyperparameter tuning', FALSE, 3),
(40034, 4003, 'Drop the time column before splitting', FALSE, 4),
(40041, 4004, 'A feature contains information that is only known after the target outcome occurs', TRUE, 1),
(40042, 4004, 'Columns are renamed before training', FALSE, 2),
(40043, 4004, 'The train set is larger than the test set', FALSE, 3),
(40044, 4004, 'A notebook run includes markdown cells', FALSE, 4),
(40051, 4005, 'Precision-recall based metrics such as F1 or PR-AUC', TRUE, 1),
(40052, 4005, 'Only raw accuracy because class imbalance does not matter', FALSE, 2),
(40053, 4005, 'Character count of the feature names', FALSE, 3),
(40054, 4005, 'Mean absolute error for all classifiers', FALSE, 4),
(40061, 4006, 'Scaling parameters should be fit on training data and applied consistently inside the pipeline', TRUE, 1),
(40062, 4006, 'Scaling should be calculated once using the full dataset before splitting', FALSE, 2),
(40063, 4006, 'Scaling only matters after deployment', FALSE, 3),
(40064, 4006, 'Scaling is never needed for gradient-based methods', FALSE, 4),
(40071, 4007, 'Model or data drift', TRUE, 1),
(40072, 4007, 'Label smoothing', FALSE, 2),
(40073, 4007, 'Feature hashing', FALSE, 3),
(40074, 4007, 'Regularization collapse', FALSE, 4),
(40081, 4008, 'Track online performance, feature distributions, and alert on statistically meaningful shifts', TRUE, 1),
(40082, 4008, 'Only watch CPU usage on the training laptop', FALSE, 2),
(40083, 4008, 'Disable logging so production is faster', FALSE, 3),
(40084, 4008, 'Retrain every hour without comparing data or metrics', FALSE, 4),

(50011, 5001, 'Provisioning and managing infrastructure through version-controlled definitions', TRUE, 1),
(50012, 5001, 'Creating servers manually in a console without audit history', FALSE, 2),
(50013, 5001, 'Storing secrets directly in shell history', FALSE, 3),
(50014, 5001, 'Editing production instances until they look correct', FALSE, 4),
(50021, 5002, 'Grant identities only the minimum permissions required for their tasks', TRUE, 1),
(50022, 5002, 'Give every engineer administrator access by default', FALSE, 2),
(50023, 5002, 'Use one shared root credential everywhere', FALSE, 3),
(50024, 5002, 'Disable audit logs to reduce noise', FALSE, 4),
(50031, 5003, 'Build the artifact and run automated quality checks before promotion', TRUE, 1),
(50032, 5003, 'Delete old branches as a mandatory quality signal', FALSE, 2),
(50033, 5003, 'Skip tests to accelerate deployments to production', FALSE, 3),
(50034, 5003, 'Rotate all cloud secrets on every commit regardless of need', FALSE, 4),
(50041, 5004, 'They keep traffic away from pods that are not ready to serve requests', TRUE, 1),
(50042, 5004, 'They replace the need for observability and logs', FALSE, 2),
(50043, 5004, 'They shrink container images automatically', FALSE, 3),
(50044, 5004, 'They make rolling updates unnecessary', FALSE, 4),
(50051, 5005, 'In a secret manager or orchestrator secret mechanism with controlled access', TRUE, 1),
(50052, 5005, 'Hard-coded in the Dockerfile', FALSE, 2),
(50053, 5005, 'Committed in a private repository for convenience', FALSE, 3),
(50054, 5005, 'Printed into CI logs so every step can read them', FALSE, 4),
(50061, 5006, 'Standard output and error so the platform can collect and route them', TRUE, 1),
(50062, 5006, 'Inside random files in the container image only', FALSE, 2),
(50063, 5006, 'Only on a developer laptop over SSH', FALSE, 3),
(50064, 5006, 'As commit messages in git after each deploy', FALSE, 4),
(50071, 5007, 'It allows safer cutover and simpler rollback between two environments', TRUE, 1),
(50072, 5007, 'It guarantees zero bugs without tests', FALSE, 2),
(50073, 5007, 'It removes the need for monitoring during releases', FALSE, 3),
(50074, 5007, 'It only works for static frontend sites', FALSE, 4),
(50081, 5008, 'A reliability target such as 99.9 percent successful requests over a period', TRUE, 1),
(50082, 5008, 'A log message printed when a deployment finishes', FALSE, 2),
(50083, 5008, 'The total number of YAML files in the repository', FALSE, 3),
(50084, 5008, 'A rule that all servers must use the same CPU type', FALSE, 4);
