INSERT INTO assessment_questions (id, question_text, stage) VALUES
    (1, 'I enjoy solving logical puzzles and algorithmic problems.', 1),
    (2, 'I like creating visual concepts and user interfaces.', 1),
    (3, 'I enjoy working with numbers, trends, and datasets.', 1),
    (4, 'I am comfortable communicating ideas and collaborating across teams.', 1),
    (5, 'I like leading people and making strategic decisions.', 1),
    (6, 'How much hands-on programming experience do you currently have?', 2),
    (7, 'How familiar are you with data tools (Excel, SQL, Python, BI tools)?', 2),
    (8, 'How often do you use design tools (Figma, Adobe XD, Sketch)?', 2),
    (9, 'How often do you run marketing activities (campaigns, SEO, content)?', 2),
    (10, 'How much project or people management exposure do you have?', 2),
    (11, 'Would you enjoy building scalable backend services and APIs?', 3),
    (12, 'Would you enjoy building dashboards and predictive models from data?', 3),
    (13, 'Would you enjoy owning product strategy and roadmap decisions?', 3),
    (14, 'Would you enjoy crafting user experiences and visual systems?', 3),
    (15, 'Would you enjoy planning growth campaigns and customer acquisition?', 3),
    (16, 'Would you enjoy end-to-end full stack application delivery?', 3),
    (17, 'Would you enjoy automating infrastructure and deployment pipelines?', 3),
    (18, 'Would you enjoy securing systems and handling threat analysis?', 3);

INSERT INTO assessment_options (id, question_id, option_text, weight_json) VALUES
    (1, 1, 'Strongly agree', '{"SOFTWARE_ENGINEERING":3,"JAVA_BACKEND_DEVELOPER":3,"FULL_STACK_DEVELOPER":2,"DATA_SCIENCE":2,"DATA_SCIENTIST":2,"DEVOPS_ENGINEER":2,"QA_ENGINEER":2,"CYBERSECURITY_ANALYST":2,"DATA_ANALYST":1,"FRONTEND_DEVELOPER":1}'),
    (2, 1, 'Agree', '{"SOFTWARE_ENGINEERING":2,"JAVA_BACKEND_DEVELOPER":2,"FULL_STACK_DEVELOPER":2,"DATA_SCIENCE":1,"DATA_SCIENTIST":1,"DEVOPS_ENGINEER":1,"QA_ENGINEER":1,"CYBERSECURITY_ANALYST":1}'),
    (3, 1, 'Neutral', '{}'),
    (4, 1, 'Disagree', '{"DESIGN":1,"UI_UX_DESIGNER":1,"MARKETING":1,"PRODUCT_MANAGER":1}'),
    (5, 2, 'Strongly agree', '{"DESIGN":3,"UI_UX_DESIGNER":3,"FRONTEND_DEVELOPER":2,"MARKETING":2,"FULL_STACK_DEVELOPER":1,"PRODUCT_MANAGEMENT":1,"PRODUCT_MANAGER":1}'),
    (6, 2, 'Agree', '{"DESIGN":2,"UI_UX_DESIGNER":2,"FRONTEND_DEVELOPER":1,"MARKETING":1,"PRODUCT_MANAGEMENT":1}'),
    (7, 2, 'Neutral', '{}'),
    (8, 2, 'Disagree', '{"JAVA_BACKEND_DEVELOPER":1,"DEVOPS_ENGINEER":1,"DATA_ANALYST":1}'),
    (9, 3, 'Strongly agree', '{"DATA_SCIENCE":3,"DATA_SCIENTIST":3,"DATA_ANALYST":3,"SOFTWARE_ENGINEERING":1,"QA_ENGINEER":1}'),
    (10, 3, 'Agree', '{"DATA_SCIENCE":2,"DATA_SCIENTIST":2,"DATA_ANALYST":2,"SOFTWARE_ENGINEERING":1}'),
    (11, 3, 'Neutral', '{}'),
    (12, 3, 'Disagree', '{"DESIGN":1,"UI_UX_DESIGNER":1,"MARKETING":1}'),
    (13, 4, 'Strongly agree', '{"PRODUCT_MANAGEMENT":3,"PRODUCT_MANAGER":3,"MARKETING":3,"DESIGN":2,"UI_UX_DESIGNER":1,"QA_ENGINEER":1}'),
    (14, 4, 'Agree', '{"PRODUCT_MANAGEMENT":2,"PRODUCT_MANAGER":2,"MARKETING":2,"DESIGN":1}'),
    (15, 4, 'Neutral', '{}'),
    (16, 4, 'Disagree', '{"JAVA_BACKEND_DEVELOPER":1,"CYBERSECURITY_ANALYST":1}'),
    (17, 5, 'Strongly agree', '{"PRODUCT_MANAGEMENT":3,"PRODUCT_MANAGER":3,"MARKETING":2,"DEVOPS_ENGINEER":1,"CYBERSECURITY_ANALYST":1,"SOFTWARE_ENGINEERING":1}'),
    (18, 5, 'Agree', '{"PRODUCT_MANAGEMENT":2,"PRODUCT_MANAGER":2,"MARKETING":1,"SOFTWARE_ENGINEERING":1}'),
    (19, 5, 'Neutral', '{}'),
    (20, 5, 'Disagree', '{"DESIGN":1,"UI_UX_DESIGNER":1,"DATA_ANALYST":1}'),
    (21, 6, 'Built multiple production-grade applications', '{"SOFTWARE_ENGINEERING":3,"JAVA_BACKEND_DEVELOPER":3,"FULL_STACK_DEVELOPER":3,"FRONTEND_DEVELOPER":2,"DEVOPS_ENGINEER":1}'),
    (22, 6, 'Built a few projects and understand core concepts', '{"SOFTWARE_ENGINEERING":2,"JAVA_BACKEND_DEVELOPER":2,"FULL_STACK_DEVELOPER":2,"FRONTEND_DEVELOPER":1,"QA_ENGINEER":1}'),
    (23, 6, 'Only basic coding practice', '{"DATA_ANALYST":1,"QA_ENGINEER":1}'),
    (24, 6, 'No experience yet', '{"MARKETING":1,"DESIGN":1,"PRODUCT_MANAGER":1}'),
    (25, 7, 'Advanced (build models/dashboards independently)', '{"DATA_SCIENCE":3,"DATA_SCIENTIST":3,"DATA_ANALYST":3,"SOFTWARE_ENGINEERING":1}'),
    (26, 7, 'Intermediate (can clean, query, and visualize data)', '{"DATA_SCIENCE":2,"DATA_SCIENTIST":2,"DATA_ANALYST":2,"PRODUCT_MANAGER":1}'),
    (27, 7, 'Beginner', '{"PRODUCT_MANAGEMENT":1,"MARKETING":1}'),
    (28, 7, 'No exposure', '{"DESIGN":1,"UI_UX_DESIGNER":1}'),
    (29, 8, 'Frequent and confident user of design tools', '{"DESIGN":3,"UI_UX_DESIGNER":3,"FRONTEND_DEVELOPER":2}'),
    (30, 8, 'Occasional usage', '{"DESIGN":2,"UI_UX_DESIGNER":2,"FRONTEND_DEVELOPER":1,"PRODUCT_MANAGER":1}'),
    (31, 8, 'Exploring basics', '{"MARKETING":1,"PRODUCT_MANAGEMENT":1}'),
    (32, 8, 'No exposure', '{"JAVA_BACKEND_DEVELOPER":1,"DEVOPS_ENGINEER":1}'),
    (33, 9, 'I have planned and executed multiple campaigns', '{"MARKETING":3,"PRODUCT_MANAGER":2,"PRODUCT_MANAGEMENT":2}'),
    (34, 9, 'I have done some campaign/content work', '{"MARKETING":2,"PRODUCT_MANAGEMENT":1,"PRODUCT_MANAGER":1}'),
    (35, 9, 'I only understand the basics', '{"DESIGN":1,"UI_UX_DESIGNER":1}'),
    (36, 9, 'No exposure', '{"SOFTWARE_ENGINEERING":1,"DATA_SCIENCE":1}'),
    (37, 10, 'I have led teams/projects with ownership', '{"PRODUCT_MANAGER":3,"PRODUCT_MANAGEMENT":3,"MARKETING":2,"DEVOPS_ENGINEER":1}'),
    (38, 10, 'I have managed small tasks/coordination', '{"PRODUCT_MANAGER":2,"PRODUCT_MANAGEMENT":2,"MARKETING":1}'),
    (39, 10, 'I am mostly an individual contributor', '{"SOFTWARE_ENGINEERING":1,"DATA_SCIENCE":1,"DESIGN":1}'),
    (40, 10, 'No management exposure', '{"JAVA_BACKEND_DEVELOPER":1,"FRONTEND_DEVELOPER":1}'),
    (41, 11, 'Very interested', '{"SOFTWARE_ENGINEERING":4,"JAVA_BACKEND_DEVELOPER":4,"FULL_STACK_DEVELOPER":3,"DEVOPS_ENGINEER":2,"CYBERSECURITY_ANALYST":1}'),
    (42, 11, 'Somewhat interested', '{"SOFTWARE_ENGINEERING":2,"JAVA_BACKEND_DEVELOPER":2,"FULL_STACK_DEVELOPER":2,"DEVOPS_ENGINEER":1}'),
    (43, 11, 'Not sure', '{"SOFTWARE_ENGINEERING":1,"FULL_STACK_DEVELOPER":1}'),
    (44, 11, 'Not interested', '{"DESIGN":1,"UI_UX_DESIGNER":1,"MARKETING":1}'),
    (45, 12, 'Very interested', '{"DATA_SCIENCE":4,"DATA_SCIENTIST":4,"DATA_ANALYST":4,"SOFTWARE_ENGINEERING":1}'),
    (46, 12, 'Somewhat interested', '{"DATA_SCIENCE":2,"DATA_SCIENTIST":2,"DATA_ANALYST":2}'),
    (47, 12, 'Not sure', '{"DATA_ANALYST":1,"PRODUCT_MANAGER":1}'),
    (48, 12, 'Not interested', '{"DESIGN":1,"MARKETING":1}'),
    (49, 13, 'Very interested', '{"PRODUCT_MANAGEMENT":4,"PRODUCT_MANAGER":4,"MARKETING":2}'),
    (50, 13, 'Somewhat interested', '{"PRODUCT_MANAGEMENT":2,"PRODUCT_MANAGER":2,"MARKETING":1}'),
    (51, 13, 'Not sure', '{"PRODUCT_MANAGEMENT":1,"PRODUCT_MANAGER":1}'),
    (52, 13, 'Not interested', '{"SOFTWARE_ENGINEERING":1,"DATA_SCIENCE":1}'),
    (53, 14, 'Very interested', '{"DESIGN":4,"UI_UX_DESIGNER":4,"FRONTEND_DEVELOPER":2}'),
    (54, 14, 'Somewhat interested', '{"DESIGN":2,"UI_UX_DESIGNER":2,"FRONTEND_DEVELOPER":1}'),
    (55, 14, 'Not sure', '{"DESIGN":1,"UI_UX_DESIGNER":1}'),
    (56, 14, 'Not interested', '{"JAVA_BACKEND_DEVELOPER":1,"CYBERSECURITY_ANALYST":1}'),
    (57, 15, 'Very interested', '{"MARKETING":4,"PRODUCT_MANAGER":2,"PRODUCT_MANAGEMENT":2}'),
    (58, 15, 'Somewhat interested', '{"MARKETING":2,"PRODUCT_MANAGER":1,"PRODUCT_MANAGEMENT":1}'),
    (59, 15, 'Not sure', '{"MARKETING":1}'),
    (60, 15, 'Not interested', '{"DATA_SCIENCE":1,"JAVA_BACKEND_DEVELOPER":1}'),
    (61, 16, 'Very interested', '{"FULL_STACK_DEVELOPER":4,"SOFTWARE_ENGINEERING":3,"FRONTEND_DEVELOPER":3,"JAVA_BACKEND_DEVELOPER":3,"DEVOPS_ENGINEER":1,"QA_ENGINEER":1}'),
    (62, 16, 'Somewhat interested', '{"FULL_STACK_DEVELOPER":2,"SOFTWARE_ENGINEERING":2,"FRONTEND_DEVELOPER":2,"JAVA_BACKEND_DEVELOPER":2}'),
    (63, 16, 'Not sure', '{"FULL_STACK_DEVELOPER":1,"SOFTWARE_ENGINEERING":1}'),
    (64, 16, 'Not interested', '{"DESIGN":1,"MARKETING":1}'),
    (65, 17, 'Very interested', '{"DEVOPS_ENGINEER":4,"SOFTWARE_ENGINEERING":2,"JAVA_BACKEND_DEVELOPER":2,"FULL_STACK_DEVELOPER":1}'),
    (66, 17, 'Somewhat interested', '{"DEVOPS_ENGINEER":2,"SOFTWARE_ENGINEERING":1,"JAVA_BACKEND_DEVELOPER":1}'),
    (67, 17, 'Not sure', '{"DEVOPS_ENGINEER":1}'),
    (68, 17, 'Not interested', '{"DESIGN":1,"MARKETING":1}'),
    (69, 18, 'Very interested', '{"CYBERSECURITY_ANALYST":4,"DEVOPS_ENGINEER":2,"SOFTWARE_ENGINEERING":1,"QA_ENGINEER":1}'),
    (70, 18, 'Somewhat interested', '{"CYBERSECURITY_ANALYST":2,"DEVOPS_ENGINEER":1,"QA_ENGINEER":1}'),
    (71, 18, 'Not sure', '{"CYBERSECURITY_ANALYST":1}'),
    (72, 18, 'Not interested', '{"DESIGN":1,"MARKETING":1}');

INSERT INTO career_phases (id, career_track, phase_order, phase_title, description) VALUES
    (1, 'SOFTWARE_ENGINEERING', 1, 'Foundation', 'Build core coding and computer science fundamentals.'),
    (2, 'SOFTWARE_ENGINEERING', 2, 'Execution', 'Build practical software projects and delivery habits.'),
    (3, 'SOFTWARE_ENGINEERING', 3, 'Acceleration', 'Optimize for interviews, collaboration, and growth.'),
    (4, 'DATA_SCIENCE', 1, 'Foundation', 'Develop statistics, Python, and data manipulation skills.'),
    (5, 'DATA_SCIENCE', 2, 'Execution', 'Ship real projects using end-to-end data workflows.'),
    (6, 'DATA_SCIENCE', 3, 'Acceleration', 'Scale model impact and communication quality.'),
    (7, 'PRODUCT_MANAGEMENT', 1, 'Foundation', 'Build product thinking and market awareness.'),
    (8, 'PRODUCT_MANAGEMENT', 2, 'Execution', 'Practice feature planning and stakeholder execution.'),
    (9, 'PRODUCT_MANAGEMENT', 3, 'Acceleration', 'Drive measurable product outcomes.'),
    (10, 'DESIGN', 1, 'Foundation', 'Build UX principles and design tool fluency.'),
    (11, 'DESIGN', 2, 'Execution', 'Create practical case studies and design systems.'),
    (12, 'DESIGN', 3, 'Acceleration', 'Improve portfolio depth and critique quality.'),
    (13, 'MARKETING', 1, 'Foundation', 'Learn audience research and channel fundamentals.'),
    (14, 'MARKETING', 2, 'Execution', 'Run and analyze practical campaigns.'),
    (15, 'MARKETING', 3, 'Acceleration', 'Scale growth with strategic experiments.'),
    (16, 'JAVA_BACKEND_DEVELOPER', 1, 'Foundation', 'Master Java and backend engineering basics.'),
    (17, 'JAVA_BACKEND_DEVELOPER', 2, 'Execution', 'Build secure and scalable backend services.'),
    (18, 'JAVA_BACKEND_DEVELOPER', 3, 'Acceleration', 'Improve performance and architecture quality.'),
    (19, 'FRONTEND_DEVELOPER', 1, 'Foundation', 'Learn UI foundations and modern JavaScript.'),
    (20, 'FRONTEND_DEVELOPER', 2, 'Execution', 'Build responsive and accessible applications.'),
    (21, 'FRONTEND_DEVELOPER', 3, 'Acceleration', 'Optimize UX quality and frontend performance.'),
    (22, 'FULL_STACK_DEVELOPER', 1, 'Foundation', 'Strengthen frontend and backend fundamentals.'),
    (23, 'FULL_STACK_DEVELOPER', 2, 'Execution', 'Build complete end-to-end products.'),
    (24, 'FULL_STACK_DEVELOPER', 3, 'Acceleration', 'Improve deployment, quality, and scale.'),
    (25, 'DATA_ANALYST', 1, 'Foundation', 'Build query, spreadsheet, and analytics basics.'),
    (26, 'DATA_ANALYST', 2, 'Execution', 'Deliver business dashboards and analysis reports.'),
    (27, 'DATA_ANALYST', 3, 'Acceleration', 'Improve analytics storytelling and influence.'),
    (28, 'DATA_SCIENTIST', 1, 'Foundation', 'Build advanced math and machine learning fundamentals.'),
    (29, 'DATA_SCIENTIST', 2, 'Execution', 'Train, evaluate, and ship ML workflows.'),
    (30, 'DATA_SCIENTIST', 3, 'Acceleration', 'Productionize and monitor model value.'),
    (31, 'DEVOPS_ENGINEER', 1, 'Foundation', 'Build Linux, networking, and automation basics.'),
    (32, 'DEVOPS_ENGINEER', 2, 'Execution', 'Implement CI/CD and infrastructure as code.'),
    (33, 'DEVOPS_ENGINEER', 3, 'Acceleration', 'Scale reliability and platform maturity.'),
    (34, 'QA_ENGINEER', 1, 'Foundation', 'Learn quality engineering and test strategy basics.'),
    (35, 'QA_ENGINEER', 2, 'Execution', 'Create and automate robust test suites.'),
    (36, 'QA_ENGINEER', 3, 'Acceleration', 'Drive quality metrics and release confidence.'),
    (37, 'UI_UX_DESIGNER', 1, 'Foundation', 'Build user research and interface design fundamentals.'),
    (38, 'UI_UX_DESIGNER', 2, 'Execution', 'Deliver usability-focused product design outcomes.'),
    (39, 'UI_UX_DESIGNER', 3, 'Acceleration', 'Scale design systems and user impact.'),
    (40, 'PRODUCT_MANAGER', 1, 'Foundation', 'Build business, user, and product intuition.'),
    (41, 'PRODUCT_MANAGER', 2, 'Execution', 'Lead roadmap delivery and cross-team alignment.'),
    (42, 'PRODUCT_MANAGER', 3, 'Acceleration', 'Drive product outcomes with metrics and strategy.'),
    (43, 'CYBERSECURITY_ANALYST', 1, 'Foundation', 'Build security foundations and threat awareness.'),
    (44, 'CYBERSECURITY_ANALYST', 2, 'Execution', 'Practice defensive operations and incident workflows.'),
    (45, 'CYBERSECURITY_ANALYST', 3, 'Acceleration', 'Strengthen security posture and response readiness.');

INSERT INTO career_goal_templates (id, career_track, phase_id, title, description, category, priority, default_order) VALUES
    (1, 'SOFTWARE_ENGINEERING', 1, 'Master data structures and algorithms', 'Focus on arrays, trees, graphs, and complexity analysis.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (2, 'SOFTWARE_ENGINEERING', 1, 'Complete Java or JavaScript fundamentals', 'Build fluency in one backend or full stack language.', 'LEARNING', 'MEDIUM', 2),
    (3, 'SOFTWARE_ENGINEERING', 2, 'Build a production-style API project', 'Create and document a REST API with persistence.', 'PROJECT', 'HIGH', 1),
    (4, 'SOFTWARE_ENGINEERING', 3, 'Create interview preparation plan', 'Set weekly mock interviews and system design practice.', 'CAREER_GROWTH', 'HIGH', 1),
    (5, 'DATA_SCIENCE', 4, 'Strengthen statistics and probability', 'Cover inference, distributions, and hypothesis testing.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (6, 'DATA_SCIENCE', 4, 'Learn Python data stack deeply', 'Practice pandas, numpy, and scikit-learn workflows.', 'LEARNING', 'MEDIUM', 2),
    (7, 'DATA_SCIENCE', 5, 'Build an end-to-end ML project', 'From data cleaning to model evaluation and presentation.', 'PROJECT', 'HIGH', 1),
    (8, 'DATA_SCIENCE', 6, 'Publish portfolio with business impact', 'Document outcomes, assumptions, and measurable value.', 'CAREER_GROWTH', 'HIGH', 1),
    (9, 'PRODUCT_MANAGEMENT', 7, 'Study product discovery fundamentals', 'Learn user interviews, problem framing, and prioritization.', 'LEARNING', 'MEDIUM', 1),
    (10, 'PRODUCT_MANAGEMENT', 7, 'Build product metrics framework', 'Define north-star metric and supporting KPI tree.', 'SKILL_DEVELOPMENT', 'HIGH', 2),
    (11, 'PRODUCT_MANAGEMENT', 8, 'Write a complete PRD for one feature', 'Draft requirements, scope, and release criteria.', 'PROJECT', 'HIGH', 1),
    (12, 'PRODUCT_MANAGEMENT', 9, 'Lead a feature outcome retrospective', 'Analyze experiment results and decision quality.', 'CAREER_GROWTH', 'HIGH', 1),
    (13, 'DESIGN', 10, 'Improve visual hierarchy and typography', 'Practice composition, spacing, and accessibility.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (14, 'DESIGN', 10, 'Master Figma workflows', 'Use components, variants, auto-layout, and prototyping.', 'LEARNING', 'MEDIUM', 2),
    (15, 'DESIGN', 11, 'Design a full product case study', 'Include user flow, wireframes, and high-fidelity screens.', 'PROJECT', 'HIGH', 1),
    (16, 'DESIGN', 12, 'Present portfolio to mentors for critique', 'Collect feedback and iterate portfolio quality.', 'CAREER_GROWTH', 'MEDIUM', 1),
    (17, 'MARKETING', 13, 'Learn core growth channels', 'Cover SEO, paid ads, email, and social distribution.', 'LEARNING', 'MEDIUM', 1),
    (18, 'MARKETING', 13, 'Build campaign planning checklist', 'Define goals, audience, messaging, and KPIs.', 'SKILL_DEVELOPMENT', 'HIGH', 2),
    (19, 'MARKETING', 14, 'Run and measure one live campaign', 'Track conversion funnel and optimize performance.', 'PROJECT', 'HIGH', 1),
    (20, 'MARKETING', 15, 'Create quarterly growth playbook', 'Summarize winning experiments and channel strategy.', 'CAREER_GROWTH', 'HIGH', 1),
    (21, 'JAVA_BACKEND_DEVELOPER', 16, 'Strengthen Java and OOP mastery', 'Focus on collections, concurrency, and clean architecture.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (22, 'JAVA_BACKEND_DEVELOPER', 16, 'Learn Spring Boot internals', 'Understand dependency injection, web, and data layers.', 'LEARNING', 'MEDIUM', 2),
    (23, 'JAVA_BACKEND_DEVELOPER', 17, 'Build secure backend service', 'Implement auth, validation, and robust API error handling.', 'PROJECT', 'HIGH', 1),
    (24, 'JAVA_BACKEND_DEVELOPER', 18, 'Optimize API performance', 'Profile queries and improve response latency.', 'CAREER_GROWTH', 'HIGH', 1),
    (25, 'FRONTEND_DEVELOPER', 19, 'Master semantic HTML and modern CSS', 'Build accessible layouts and reusable UI components.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (26, 'FRONTEND_DEVELOPER', 19, 'Deepen JavaScript fundamentals', 'Focus on async flow, DOM patterns, and state management.', 'LEARNING', 'MEDIUM', 2),
    (27, 'FRONTEND_DEVELOPER', 20, 'Build a responsive frontend project', 'Implement API integration and interactive UX flows.', 'PROJECT', 'HIGH', 1),
    (28, 'FRONTEND_DEVELOPER', 21, 'Improve Lighthouse and accessibility scores', 'Raise performance and usability baselines.', 'CAREER_GROWTH', 'MEDIUM', 1),
    (29, 'FULL_STACK_DEVELOPER', 22, 'Reinforce full stack architecture basics', 'Review frontend, backend, and database interaction design.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (30, 'FULL_STACK_DEVELOPER', 22, 'Learn deployment and environment workflows', 'Understand build pipelines and runtime configuration.', 'LEARNING', 'MEDIUM', 2),
    (31, 'FULL_STACK_DEVELOPER', 23, 'Build a full product from idea to release', 'Deliver full stack app with auth, data, and UI.', 'PROJECT', 'HIGH', 1),
    (32, 'FULL_STACK_DEVELOPER', 24, 'Improve reliability with monitoring', 'Add logging, alerts, and operational checklists.', 'CAREER_GROWTH', 'MEDIUM', 1),
    (33, 'DATA_ANALYST', 25, 'Master SQL and spreadsheet analytics', 'Practice joins, aggregations, and dashboard-ready datasets.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (34, 'DATA_ANALYST', 25, 'Learn BI tooling workflows', 'Explore dashboard building and stakeholder reporting.', 'LEARNING', 'MEDIUM', 2),
    (35, 'DATA_ANALYST', 26, 'Build business KPI dashboard', 'Track retention, conversion, and revenue insights.', 'PROJECT', 'HIGH', 1),
    (36, 'DATA_ANALYST', 27, 'Present monthly insights report', 'Deliver clear recommendations with data evidence.', 'CAREER_GROWTH', 'MEDIUM', 1),
    (37, 'DATA_SCIENTIST', 28, 'Strengthen ML and math foundations', 'Revise supervised/unsupervised learning and model metrics.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (38, 'DATA_SCIENTIST', 28, 'Study feature engineering patterns', 'Learn robust data preprocessing and feature selection.', 'LEARNING', 'MEDIUM', 2),
    (39, 'DATA_SCIENTIST', 29, 'Ship a model experimentation project', 'Document baselines, tuning, and validation strategy.', 'PROJECT', 'HIGH', 1),
    (40, 'DATA_SCIENTIST', 30, 'Productionize one ML pipeline', 'Handle monitoring, drift checks, and retraining flow.', 'CAREER_GROWTH', 'HIGH', 1),
    (41, 'DEVOPS_ENGINEER', 31, 'Learn Linux and networking essentials', 'Build command-line and infrastructure troubleshooting skills.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (42, 'DEVOPS_ENGINEER', 31, 'Practice infrastructure as code basics', 'Use Terraform or equivalent provisioning tools.', 'LEARNING', 'MEDIUM', 2),
    (43, 'DEVOPS_ENGINEER', 32, 'Set up CI/CD for one service', 'Automate build, test, and deployment pipelines.', 'PROJECT', 'HIGH', 1),
    (44, 'DEVOPS_ENGINEER', 33, 'Implement SLO and incident playbook', 'Define reliability goals and response workflow.', 'CAREER_GROWTH', 'HIGH', 1),
    (45, 'QA_ENGINEER', 34, 'Learn testing strategy fundamentals', 'Cover functional, regression, and risk-based testing.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (46, 'QA_ENGINEER', 34, 'Improve automation scripting skills', 'Practice API and UI test automation tooling.', 'LEARNING', 'MEDIUM', 2),
    (47, 'QA_ENGINEER', 35, 'Build automated regression suite', 'Create stable tests for critical user journeys.', 'PROJECT', 'HIGH', 1),
    (48, 'QA_ENGINEER', 36, 'Establish quality metrics dashboard', 'Track defect leakage and release health trends.', 'CAREER_GROWTH', 'MEDIUM', 1),
    (49, 'UI_UX_DESIGNER', 37, 'Build UX research toolkit', 'Practice interview scripts and usability test plans.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (50, 'UI_UX_DESIGNER', 37, 'Deepen interaction design skills', 'Improve flows, states, and interface clarity.', 'LEARNING', 'MEDIUM', 2),
    (51, 'UI_UX_DESIGNER', 38, 'Deliver a usability-driven redesign', 'Measure before/after task completion improvements.', 'PROJECT', 'HIGH', 1),
    (52, 'UI_UX_DESIGNER', 39, 'Create scalable design system assets', 'Document reusable patterns and accessibility guidance.', 'CAREER_GROWTH', 'MEDIUM', 1),
    (53, 'PRODUCT_MANAGER', 40, 'Strengthen market and user analysis', 'Practice competitive scans and opportunity sizing.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (54, 'PRODUCT_MANAGER', 40, 'Build prioritization framework', 'Use impact-effort and strategic scoring methods.', 'LEARNING', 'MEDIUM', 2),
    (55, 'PRODUCT_MANAGER', 41, 'Lead cross-functional launch plan', 'Coordinate scope, timeline, and communication.', 'PROJECT', 'HIGH', 1),
    (56, 'PRODUCT_MANAGER', 42, 'Run outcome-based roadmap review', 'Adjust roadmap using performance evidence.', 'CAREER_GROWTH', 'HIGH', 1),
    (57, 'CYBERSECURITY_ANALYST', 43, 'Study security fundamentals and threats', 'Cover CIA triad, OWASP, and attack vectors.', 'SKILL_DEVELOPMENT', 'HIGH', 1),
    (58, 'CYBERSECURITY_ANALYST', 43, 'Practice vulnerability assessment tools', 'Use scanners and manual verification workflows.', 'LEARNING', 'MEDIUM', 2),
    (59, 'CYBERSECURITY_ANALYST', 44, 'Build incident response checklist', 'Define triage, containment, and reporting steps.', 'PROJECT', 'HIGH', 1),
    (60, 'CYBERSECURITY_ANALYST', 45, 'Create security posture improvement plan', 'Prioritize controls and audit readiness tasks.', 'CAREER_GROWTH', 'HIGH', 1);
